### ISSUE TITLE
Adding Nextcloud as Source results in 405 Method not allowed

### ISSUE THREAD

**Issue by daehruoydeef** [icidasset/diffuse#140]
I followed the "Adding Sources" procedure and added my host, username, password and the directory which looks in my case like this.   /remote.php/webdav/

I uploaded .wav and .mp3 but the little error next to the source is telling my that the method is not allowed. Since 4XX are Client errors I expect it to be a bug inside the programm. I am running nextcloud 15 and the latest AppImage of Diffuse on NitruxOS.

**Comment by icidasset** [comment]
Hey @daehruoydeef 
Thanks for creating this issue!
I don't know much about nextcloud, but I'll do my best.

_Usually you'll get a 405 because either:_
- The directory (ie. path) isn't correct (maybe webdav is configured on a different path?)
- Some configuration forbids the client (diffuse) from connecting with the nextcloud server

_A few questions:_
- Have you tried the alternative webdav path? (it looks like this: `/remote.php/dav/files/USERNAME`)
- Have you tried creating another account and using that username/password combination?
- What does the `host` address look like? (or in other words, where is the nextcloud server located)
- Are you using HTTP or HTTPS?

PS. `.wav` is not supported at the moment, will be in V2 though (work in progress)

---

Just for reference, this is my setup and works for me.
<img width="814" alt="screenshot 2019-02-22 at 12 34 37" src="https://user-images.githubusercontent.com/296665/53240160-47de6280-369e-11e9-9a4c-871fdb1becb2.png">
Nextcloud on a local VM using https://www.hanssonit.se/nextcloud-vm/

**Comment by daehruoydeef** [comment]
![image](https://user-images.githubusercontent.com/36965591/53247750-76673800-36b4-11e9-8f8b-24dbf1de789a.png)

this how my setup now looks. The Directory path is the one provided by nextcloud. Other Applications are available to sync my calendar and contacts via this webdav. I changed the directory to the other format but this does not work either and I feel like this is the wrong way. 

As you can see I am using https but also tried http with no Luck either.

**Comment by icidasset** [comment]
So, I made an account on the same service you have (`next-cloud.org`) and I can replicate the issue. For some weird reason, that `next-cloud.org` service you're using doesn't like the `Host` request header even though that's a standard thing 😕 

**In any case, I released Diffuse `v1.0.2` which removes that header from the request and thus fixes your issue.**

PS. I found that playing music from this `next-cloud.org` webdav is extremely slow, not sure it's because I'm using the free tier. Just wanted you to know, it isn't supposed to be this slow.
