### ISSUE TITLE
IPFS connection errors with IPFS Desktop

### ISSUE THREAD

**Issue by autonome** [icidasset/diffuse#163]
I'm running IPFS Desktop, and when I try to log in using the IPFS option, I get an error saying it cannot access the IPFS API at http://localhost:5001.

I have confirmed that IPFS Desktop is running, and is on that port.

**Comment by icidasset** [comment]
Hi @autonome , thanks for creating this issue!

It could be a few things:
- Your browser blocks the communication because of mixed content (HTTPS -> HTTP)
- Your IPFS CORS settings don't allow Diffuse access (ie. `API.HTTPHeaders.Access-Control-Allow-Origin`)

One solution to both of these possible issues would be to use the [IPFS Companion](https://github.com/ipfs-shipyard/ipfs-companion) extension. This works because the Diffuse website uses DNSLink and IPFS Companion proxies it through the local gateway.

To get extra info, you could open the devtools network tab before trying to sign in. I wouldn't mind a screenshot just to be sure it isn't anything else I haven't thought of.

Thanks 😉 

---

_Note to self: I should try to show better error messages, but I'm not sure if that's possible with mixed content and cors connection problems 🤔_

**Comment by icidasset** [comment]
#169 Will add a warning when using HTTPS that will ask you to install the IPFS Companion extension.

**Comment by autonome** [comment]
Thanks for bumping - sorry I forgot to reply!

* I'm using Companion (latest) on Firefox
* I'm using IPFS Desktop (latest)
* I've configured CORS both on command line and in the settings for IPFS Desktop (just to be sure!)

**Comment by icidasset** [comment]
Thanks for the follow up @autonome !
I'm not sure what the issue is honestly.

Could you show me your CORS config and/or a screenshot of the requests in the network tab in the devtools? 🙏

**Comment by icidasset** [comment]
Thanks for the follow up @autonome !
I'm not sure what the issue is honestly.

Could you show me your CORS config and/or a screenshot of the requests in the network tab in the devtools? 🙏

**Comment by icidasset** [comment]
Friendly nudge @autonome 👋 😳

Also, is your url `https://diffuse.sh` or `http://127.0.0.1:8080/ipns/diffuse.sh/`?

**Comment by autonome** [comment]
In my CORS settings in IPFS Desktop I put "https://diffuse.sh".

<img width="544" alt="Screen Shot 2019-12-28 at 3 28 18 PM" src="https://user-images.githubusercontent.com/50103/71550499-fae6af00-2986-11ea-9889-851e64bd4905.png">

**Comment by icidasset** [comment]
Thanks @autonome ! 
It looks like you need to add `http://127.0.0.1:44999` as well in your CORS settings.
I should update the CORS instructions for the desktop-app version, sorry about that!

The desktop app starts a local web server on that address ☝️ and then the Diffuse app runs on that, not `https://diffuse.sh`.

**Comment by autonome** [comment]
YES, worked immediately after adding that to CORS settings in IPFS Desktop, and starting up Diffuse desktop app. Thanks @icidasset!

**Comment by icidasset** [comment]
Awesome! 🎉 Thanks for running through this with me, IPFS integration definitely needs some work.
