### ISSUE TITLE
Diffuse doesn't like DropBox

### ISSUE THREAD

**Issue by ghost** [icidasset/diffuse#187]
Invalid redirect_uri. It must exactly match one of the redirect URIs you've pre-configured for your app (including the path).

**Comment by icidasset** [comment]
That's odd @Xecat Which version of Diffuse are you using? `https://diffuse.sh`, the native app or are you hosting it yourself?

**Comment by Xecat** [comment]
Hey!  Sorry, I've been very busy and only found time to reply, thanks for getting back to me.

No, I'm not hosting it myself, wouldn't know how to go about that, find all terminal/programming instructions spaghetti jargon.  I'm using the native app, Version 2.2.3 (2.2.3).  

I have solved the installation issue, went round the houses for 6 hours, but got there.  Connected DropBox, and selected tracks.  However, not there's another issue.  Now, whenever I select a track to play, it doesn't do anything, other than spitting back yet another error message below the window with music tracks in it.


It says "Audio connection got interrupted, trying to reconnect ..."

Then, in red I get: "I can't play this track because of a network error. I'll try to reconnect."

**Comment by Xecat** [comment]
Sorry, forgot to mention.  I'm using:
MacBook Pro (13-inch, Early 2011)
Processor 2.7 GHz Intel Core i7
Memory 8 GB 1333 MHz DDr3
Graphics Intel HD Graphics 3000 512 MB
OS High Sierra Version 10.13.6

**Comment by icidasset** [comment]
No worries! Some people take weeks to answer. I'm already grateful that you created the issue in the first place 😉 

> I have solved the installation issue, went round the houses for 6 hours, but got there.

Oh wow, it shouldn't be this difficult. Anything I could do better in this area? What caused the issue?

> Then, in red I get: "I can't play this track because of a network error. I'll try to reconnect."

It's probably that the browser (ie. app) can't play the audio file. I just released a new version that should show the correct error message, if that's the case.

**What's the extension of the audio file?** You can also send it to me, if you want me to try it out.
