### ISSUE TITLE
Sign in with Google Drive

### ISSUE THREAD

**Issue by Netherquark** [icidasset/diffuse#226]
I am unable to sign in with my Google Account in the native Windows app because of this error. Please help me out.
![image](https://user-images.githubusercontent.com/65618735/86989730-af744f80-c1b8-11ea-9ba5-43a5883812ae.png)

**Comment by icidasset** [comment]
Hey, thanks for creating this issue!

Damn it, seems like Google changed a few things again 😞 
Still works when using the app in your standard browser though https://diffuse.sh

In any case, I'll see how I can fix this in v3 🤔

**Comment by icidasset** [comment]
Ok, scratch that, managed to get a quick fix in.
Try out [v2.5.4](https://github.com/icidasset/diffuse/releases/tag/2.5.4) and see if that fixes it for you.

**Comment by Netherquark** [comment]
THANK YOU YOU ARE THE BEST I FINALLY DONT HAVE TO LISTEN TO SPOTIFY ADS. ITS REALLY A BLESSING.
PS. Is there a mobile client for diffuse? If not, is there anything in the works 🥺. Looking forward to it. You are the literal best. People like you are what keep the FOSS community kickin n alive ♥.

**Comment by icidasset** [comment]
Haha, thanks @Netherquark I appreciate it ☺️ 
Let me know if you run into any other issues.

---

You can use the web app https://diffuse.sh on mobile.
The "native" desktop version is just a wrapper around the web app by the way.

That said, there was a bug on iOS 13 (but fixed in 13.6, which is in beta right now I think),
which was causing audio-playback issues.

There's no "native" mobile client though.
Hopefully PWAs get better support and that won't be necessary.

---

Thanks again for the kind words ❤️
