### ISSUE TITLE
Make the browser storage option the default

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#295]
People shouldn't need to select a storage method first thing. User data should be stored in the browser by default, and a clear UX should be provided to move to another storage method.

**Comment by rosano** [comment]
I've only seen this in the remoteStorage library and wish it was as seamless everywhere. I have it working in my multi-protocol wrapper so that someone could start in local storage and move to fission, but it's a bit verbose: https://github.com/0dataapp/0datawrap#multiple-protocols

Might also be good to make it seamless in storagestack https://github.com/jorishermans/storagestack

I think each developer shouldn't need to build this: library-level rather than app-level…

**Comment by gityzon** [comment]
I support this.
